--autogenerated cube
cube_mesh = {
 tris = {
  triangle({vec3d(-1,1,-1), vec3d(1,1,1), vec3d(1,1,-1)}),
  triangle({vec3d(1,1,1), vec3d(-1,-1,1), vec3d(1,-1,1)}),
  triangle({vec3d(-1,1,1), vec3d(-1,-1,-1), vec3d(-1,-1,1)}),
  triangle({vec3d(1,-1,-1), vec3d(-1,-1,1), vec3d(-1,-1,-1)}),
  triangle({vec3d(1,1,-1), vec3d(1,-1,1), vec3d(1,-1,-1)}),
  triangle({vec3d(-1,1,-1), vec3d(1,-1,-1), vec3d(-1,-1,-1)}),
  triangle({vec3d(-1,1,-1), vec3d(-1,1,1), vec3d(1,1,1)}),
  triangle({vec3d(1,1,1), vec3d(-1,1,1), vec3d(-1,-1,1)}),
  triangle({vec3d(-1,1,1), vec3d(-1,1,-1), vec3d(-1,-1,-1)}),
  triangle({vec3d(1,-1,-1), vec3d(1,-1,1), vec3d(-1,-1,1)}),
  triangle({vec3d(1,1,-1), vec3d(1,1,1), vec3d(1,-1,1)}),
  triangle({vec3d(-1,1,-1), vec3d(1,1,-1), vec3d(1,-1,-1)})
 }
}
