var fs = require('fs');

Array.prototype.last = function() { let x = this.pop(); this.push(x); return x }

var text = fs.readFileSync(process.argv[2], "utf8");
var filename = process.argv[2].split("\\").last().split(".")[0];

var lines = text.split("\n");

var vecs = [];
var tris = [];
var faces = [];

var vertex_count = 0;
var face_count = 0;
var property_index = 0;

var index = {
	x : 0,
	y : 0,
	z : 0,
	red : 0,
	green : 0,
	blue : 0
};

var read_elements = false;
var isHeader = true
let i = 0;
for(; i != lines.length && isHeader; ++i) {
	var line = lines[i]
	//console.log(line);
	if(line.startsWith("element ")) {
		let p = line.split(" ");
		if(p[1] == "vertex") {
			vertex_count = Number(p[2])
		}
		if(p[1] == "face") {
			face_count = Number(p[2])
		}
		property_index = 0;
	}

	if(line.startsWith("property ")) {
		let p = line.split(" ");
		if(index[p[2]] !== undefined) {
			index[p[2]] = property_index; 
		}
		++property_index;
	}

	if(line.startsWith("end_header")) {
		isHeader = false;
	}

	if(line.startsWith("v ")) {
		//v 1.000000 1.000000 -1.000000
		line = line.substr(2);
		let vert = line.split(" ").map(s => Number(s));
		tris.push(vert);		
	}
	if(line.startsWith("f ")) {
		//f 5/1/1 3/2/1 1/3/1
		line = line.substr(2);
		let face = line.split(" ").map(s => Number(s.split("\/")[0]));
		faces.push(face);				
	}
}

for(let j = 0; j != vertex_count; ++j) {
	let line = lines[j + i];
	let p = line.split(" ");
	let vertex = {
		x : Number(p[index.x]),
		y : Number(p[index.y]),
		z : Number(p[index.z]),
	}
	vecs.push(vertex);
}
i += vertex_count;

for(let j = 0; j != face_count; ++j) {
	let line = lines[j + i];
	let p = line.split(" ").map(s => Number(s));
	//console.log(p);
	if(p[0] !== 3) throw "Face must be triangulated";
	p = p.splice(1);
	//account that lua arrays start with 1
	p = p.map(i => i+1);
	faces.push(p);
}

var filecontent = ""

function print(s) {
	filecontent += s;
}

function printLine(s) {
	print(s);
	filecontent += "\n";
}

print("--autogenerated ");
printLine(filename);

print(filename);
printLine("_mesh = {")
printLine(" vert = {")
for(let v = 0; v != vecs.length; ++v) {
	let vec = vecs[v];
	print("{");
	//print( vecs[v].join(",") )
	print(vec.x);
	print(",");
	print(vec.y);
	print(",");
	print(vec.z);
	print("}");
	if(v != tris.length -1) print(",");
	printLine("");
}
printLine(" },")

printLine(" faces = {")
printLine(" -- v1, v2, v3, distance")
for(let f = 0; f != faces.length; ++f) {
	print("{")
	print( faces[f].join(",") )
	print(",0}")
	if(f != faces.length -1) print(",");
	printLine("");
}
printLine(" }")

/*for(let i = 0; i != faces.length; ++i) {
	let face = faces[i];
	print("  triangle({")
	for(let f = 0; f != face.length; ++f) {
		let vi = face[f]-1;
		print("vec3d(");
		print(tris[vi].join(","));
		print(")");
		if(f < 2) print(", ");
	}
	print("})");
	if(i < faces.length-1) {
		print(",");
	}
	printLine("");
}*/
printLine("}")


fs.writeFileSync(filename + ".lua", filecontent);
